### ISSUE TITLE
[RADI] Connection gets stuck and never finishes

### ISSUE THREAD

**Issue by pariaspe** [JdeRobot/RoboticsAcademy#1097]
Terminal shows the same msg error in loop. This screenshot was taken using RADI v3.1.2

![bucle-error](https://user-images.githubusercontent.com/35956525/124353718-6eb2e900-dc08-11eb-8619-d40a92969a83.png)

**Comment by iamarkaj** [comment]
It is weird to see this error in RADI-3.1.2 because in RADI-3.1.1 the launching of the Drone Cat Mouse exercise was unstable + RuntimeWarning was still present. But both this problems were fixed in RADI-3.1.2 by this [commit](https://github.com/JdeRobot/RoboticsAcademy/commit/92b63577c13b78926b1860720a90ee293735d2db)

**Comment by pariaspe** [comment]
You are right @iamarkaj. This issue was fixed in v3.1.2. Closing..
