### ISSUE TITLE
[Follow Line new manager][Humble] HAL commands not being executed

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2258]
No result shown when I ran
`HAL.setV(3)`

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/75df79b5-d771-411d-82b1-908d2d1a899e)

Other exercises are working

**Comment by ReyDoran** [comment]
The reason is that HAL.py is freezing at the instruction `rclpy.spin_once(self.camera)`, preventing any user code from executing. Issue is related to a missing xserver which is needed to render the camera. The issue is moved to RoboticsApplicationManager https://github.com/JdeRobot/RoboticsApplicationManager/issues/86. Thanks for the cooperation finding the cause.
