### ISSUE TITLE
Follow line web-template error

### ISSUE THREAD

**Issue by NayOoLwin5** [JdeRobot/RoboticsAcademy#600]
Hi,
While executing the host.py file, got the following error

```
Traceback (most recent call last):
  File "host.py", line 287, in <module>
    server = Template()
  File "host.py", line 38, in __init__
    self.host = sys.argv[1]
IndexError: list index out of range
```
I have tried with all these python versions : 3.8.5 , 3.6.9  and 2.7.17. Still the same error for all.

**Comment by SakshayMahna** [comment]
Hello!
While executing the host.py file, you need to enter the IP address at which the web templates will publish their interface. Since, you may be running this in a Docker container, it is the IP address with which your Docker communicates with your native machine.

On a Windows Machine the IP address is something like 192.168.x.x. So the command would be

```bash
python host.py 192.168.x.x
```

However, if your are on a Linux Machine, the IP address would be something like 127.0.0.x. So the command would be

```bash
python host.py 127.0.0.x
```

**Since, we are using ROS Melodic, all the software has been written in Python 2.7**
