### ISSUE TITLE
Remove simulator sidebar Gzweb  RADI  (2.3 WebTemplates & Unibotics)

### ISSUE THREAD

**Issue by martaquintana** [JdeRobot/RoboticsAcademy#664]
Remove simulator sidebar Gzweb RADI ( For 2.3 WebTemplates & Unibotics)

STEPS:
Going to gzweb/http/client/gz3d.gui.js. You have to find this code (line 64946 for gzweb 1.4):

if (isWideScreen())
   {
     globalEmitter.emit('openTab', 'mainMenu', 'mainMenu');
   }
   ...

add:

globalEmitter.emit('closeTabs', true);

it would look like this:

if (isWideScreen())
    {
        globalEmitter.emit('openTab', 'mainMenu', 'mainMenu');
        globalEmitter.emit('closeTabs', true);
    }
    ...

in this way the sidebar would be hidden.

**Comment by Suhas-G** [comment]
Hello. I'm a new user of RoboticsAcademy. I was going through the Issues list, and this seemed like a nice first issue (because you have already provided a solution :smile: ). But 'gzweb/http/client/gz3d.gui.js' appears to be a minified file under [gzweb](https://github.com/osrf/gzweb) repository. So any change will have to be a pull-request on that...

I tried to find whether its possible to inject code into an iframe once its loaded. But this method is restricted by browser when the domains are different. Since 'locahost:8080' is used for gzweb and exercise can be opened just as a file, I was not able to proceed in this way.

Am I missing something? Any suggestions?

**Comment by jmplaza** [comment]
As we are replacing the Gazebo scenario viewer in all exercises from gzweb to novnc this issue has been superseded by https://github.com/JdeRobot/RoboticsAcademy/issues/790
