### ISSUE TITLE
Drop Box and Table not spawning - pick_place

### ISSUE THREAD

**Issue by predator4hack** [JdeRobot/RoboticsAcademy#802]
`roslaunch pick_place.launch` doesn't spawns table and drop boxes with errors : 
`Transform error: "vacuum_gripper8" passed to lookupTransform argument source_frame does not exist.`,
`Transform cache was not updated. Self-filtering may fail`.
`Spawn service failed. Exiting`
With warnings:
`The complete state of the robot is not yet known.  Missing gripper_joint, gripper_joint1, gripper_joint2, gripper_joint3, gripper_joint4, gripper_joint5, gripper_joint6, gripper_joint7, gripper_joint8`

**Comment by Jovian-Dsouza** [comment]
HI @predator4hack , The conveyor and the dropbox objects are not spawning because most probably your `GAZEBO_MODEL_PATH` is not set correctly.

It should be `GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:'$PWD'/src/IndustrialRobots/assets/models` instead of these `GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:'$PWD'/src/IndustrialRobotics/assets/models`.
`IndustrialRobots` instead of `IndustrialRobotics`

Looks like the [IndustrialRobots](https://github.com/JdeRobot/IndustrialRobots) Repo name was changed
